### ISSUE TITLE
Intermittent blank screen and error message after login

### ISSUE THREAD

**Issue by mariliasoaresTW** [PublicDataWorks/complaint-manager#317] opened 2023-08-14 20:50 UTC
**Describe the bug**
Intermittent bug - blank screen and an error message saying "something went wrong" when trying to login on our app

**To Reproduce**
1. Go to https://noipm-ci.herokuapp.com or https://noipm-staging.herokuapp.com
2. See a blank screen with an error message (sometimes, there is no consistent pattern found)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/67479313/0d26c595-9bc5-4dd3-ba6a-2fa6e3804a7d)

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/67479313/40a93ce3-1d91-488b-a9ab-2e03cafd215c)

**Expected behavior**
We expect that there will be always a redirect to /login

**Comment by isabelolson** [comment] 2023-09-11 17:01
**Update**: Put card back into ready for dev since cannot reproduce bug consistently enough to test/fix.

**Findings from further investigation:**  Seems as though the only difference between when the login page loads "correctly" and when there is the bug is when the following error is present:

> Refused to frame 'https://dev-68895481.okta.com/' because it violates the following Content Security Policy directive: "child-src 'self' blob:". Note that 'frame-src' was not explicitly set, so 'child-src' is used as a fallback.

**Possible solutions:** 
- https://stackoverflow.com/questions/31211359/refused-to-load-the-script-because-it-violates-the-following-content-security-po
- https://www.ibm.com/support/pages/refused-frame-xxx-because-ancestor-violates-following-content-security-policy-directive-frame-ancestors-self-errors-case-client

**Additional notes:**
- The bug has been present in all environments it seems.
- Seems as though the bug may have to do with the Content Security Policy. You can checked out more information on each organizations CSP in their  corresponding serverConfig.js in instance files. Tried comparing difference between Hawaii and New Orleans since the bug is only present for Hawaii it seems. The `self` in the above error message seems to correspond to the `self` in this file as well.

**Comment by thoughtworks-vwong** [comment] 2024-04-18 17:12
Unable to reproduce this issue. Closing this card

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/134408135/2061fbc5-90d8-4549-a2a8-6f9c4a1282a9)

**Closed** 2024-04-23 15:10 UTC
Labels: bug, 1 point, on hold
