### ISSUE TITLE
Certain fields not auto-populating in Case Details page

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#329] opened 2023-09-11 19:08 UTC
**Describe the bug**
For the new roster, district, badge/employee ID#, supervisor ID are not auto-populating when adding an Accused or Complainant.

Also supervisor is not showing for some officers like “Alijah OConnor (Id = 16886)

**To Reproduce**
Steps to reproduce the behavior for accused/complainant
1. Go to accused/complainant and add someone that has data in at least one of these fields
2. Look in Case Details page after and see if the values populate

Steps to reproduce the behavior for suprevisor
1. In the case details view look at the supervisor data and check where the code is pointing to. It should be the officer_number info (first name, last name and officer_number)
2. It seems like the code is actually pulling the windows_username or other fields when trying to find the supervisor data for an officer.

**Expected behavior**
These fields should auto-populate 

b: we found out the officers table needed updating. Here is the csv with the previous officers table + new officers + udpates to existing rows: 
[NOIPM officers 11-13-2023 - Sheet1.csv](https://github.com/PublicDataWorks/complaint-manager/files/13352152/NOIPM.officers.11-13-2023.-.Sheet1.csv)

Learnings: We learned that in this case Alijah's supervisor is Nikia Adams, officer_number 14120. For some reason we are not displaying that info on the supervisor field

**Comment by mariliasoaresTW** [comment] 2023-11-08 20:07
Updated officers roster from NOIPM: https://docs.google.com/spreadsheets/d/1Q8bq_zBpZdgz-eGXR-2-Ih3HP4NaNyaf/edit?usp=sharing&ouid=105791074404542071930&rtpof=true&sd=true

**Comment by mariliasoaresTW** [comment] 2023-11-08 23:54
CSV file for the officers table update in prod:



[NOIPM_prod_officers_11-08-23.csv](https://github.com/PublicDataWorks/complaint-manager/files/13302370/NOIPM_prod_officers_11-08-23.csv)

**Comment by mariliasoaresTW** [comment] 2023-11-08 23:54
We realized the `officers` table in prod was outdated, so we need to replace it with the CSV file above

**Comment by mariliasoaresTW** [comment] 2023-11-15 20:09
Next steps to “remove duplicates” and solve for missing data on the officers roster:


- Duplicates: For the officers that have the officer_number but no windows_username add the values from officer_number into windows_username. 

- Flag those as deprecated as they also have other fields missing (bureau, district, etc). Be careful here.

- Map district_id if district is one of the 8 districts we have on the districts table

- Update the database to add the missing data and  the created_at value filled now as “today date” for all that were updated using the new csv. Be extra careful here.

UI fixes ( to be tackled in separate cards)
a. Display “district” column on the UI but use the word “allegations” on the letters - this will show the assigment for officers who are not on “FOB”
b. Do not display officers on the UI whose created_at value is not the date of the last update.
c. Bug: why supervisor is not showing for some officers like “Alijah OConnor (Id = 16886)?

**Comment by mariliasoaresTW** [comment] 2023-12-21 22:24
Updates to my last comment:

Next steps to “remove duplicates” and solve for missing data on the officers roster:

Duplicates: For the officers that have the officer_number but no windows_username add the values from officer_number into windows_username: **to be done on #328**

Flag those as deprecated as they also have other fields missing (bureau, district, etc). Be careful here. **not relevant. Data has many missing fields**

Map district_id if district is one of the 8 districts we have on the districts table **Done as part of creating the latest officers csv file**

Update the database to add the missing data and the created_at value filled now as “today date” for all that were updated using the new csv. Be extra careful here.  **to be done on #328**

UI fixes ( to be tackled in separate cards)
a. Display work location on the UI so officers who are not assigned to a district will show their assigned location **to be done on 407**
b. Do not display officers on the UI whose created_at value is not the date of the last update. **to be done on #328**
c. Bug: why supervisor is not showing for some officers like “Alijah OConnor (Id = 16886)?  **I found out in this case we do not have the supervisor_officer_number**
 



https://github.com/PublicDataWorks/complaint-manager/issues/407

**Comment by claireholt-tw** [comment] 2024-04-11 16:59
Look at prod officers table. Sort to look at the active officers.

Look at most recent cases_officers - do they seem filled out with their data? Do they have a lot of blanks? If yes, look them up in officers and see if that data is missing in officers table too. If it's there and not making it to cases_officers, that might indicate we have a problem and our losing data on our end & should trace down how that's happening.

Note: A NULL in the officer_id column of cases_officers means the officer is unknown. it's expected that such rows don't have much data.

**Comment by justin-c-anthony** [comment] 2024-04-11 22:24
### RCA

#### Steps Taken
- We looked at the prod officers table and case_officers table.
- We filtered for known officers in case_officers table and checked to see if there were any incomplete or null fields that should not be
- We then cross referenced those known officers with the officers table.
- All the data from the officers table was being correctly pulled into the cases officers table.
- There doesn't seem to be any issues with the code displaying information in the UI that is provided from the tables. 

#### Outcome
Missing information that does not appear in the UI is coming from actual missing information in the table (null fields) and not a code issue. 

#### Follow Up

If there is a recent specific instance where a user has data but it is not showing up, we could look further into the issue.

**Comment by justin-c-anthony** [comment] 2024-04-12 15:35
Unable to reproduce bug

**Closed** 2024-04-15 17:53 UTC
Labels: bug, 1 point, new orleans
