### ISSUE TITLE
Change Auth0 Hooks and Rules to Actions

### ISSUE THREAD

**Issue by sbhamani** [PublicDataWorks/complaint-manager#418] opened 2023-12-13 16:16 UTC
Need to do this before November 2024!

https://explore.okta.com/ODU1LVFBSC02OTkAAAGP_jmdV_hTSojuezj6388FS-m3x1Eb5OvuhgmwKcHuuushhzITIqd2eMysSo4SzG_QjB6GvQs=
https://explore.okta.com/ODU1LVFBSC02OTkAAAGQCHvWwykXlhZaXnz7CM4XdC-TovI1Hx2EUl3t_d1pYeIYKsVbZVtz2BQAKM1PzK99exU7mVM=

TImebox: 2 days

DoD: Create a new card to implement the changes

**Comment by heliofreitastw** [comment] 2024-03-27 18:31
- [ ] figure out how it works today, what the problem is, and add a comment explaining it here
- [ ] read through the links provided
- [ ] explain how this will be fixed and then tested

**Comment by heliofreitastw** [comment] 2024-04-01 19:32
We use the auth0-authorization extension to manage the roles by user.  This extension will not be supported anymore when Rules and Hooks are deprecated. So, in order to continue using Auth0, we will need to change the way we manage roles on login by changing it from using the extension to using another service they support. They suggest using something called Authorization Core. 

https://auth0.com/docs/manage-users/access-control/authorization-core-vs-authorization-extension
https://community.auth0.com/t/migration-from-rules-to-actions-groups/118235
https://auth0.com/docs/manage-users/access-control/configure-core-rbac

**Comment by heliofreitastw** [comment] 2024-04-05 18:41
For this card we learned that we are using an extension to make the authorization work in Complaint Manager. This extension has manages the users, roles, and permissions. Also, this extension makes the use of a custom rule (auto generated by the extension). 
Auth0 will be discontinuing the Rules and Hooks features they provided. With that the extension used by Complaint Manager will stop working given it needs the rules. 

One possible solution we discovered is implementing the Role Based Access Control feature provided by Auth0. 

We will need to do the following:
In Auth0
- [ ] Add permissions to the API(Complaint Manager)
- [ ] Create the roles used in the Application (view roles in extension)
- [ ] Add the permissions to each role (view permissions by role in extension)
- [ ] In the Complaint Manager API settings enable RBAC and Add Permissions in the Access Token
- [ ] Assign role to user
- [ ] When everything is set up, turn off rules
- [ ] Also, turn off Hook (if existing)

in the codebase
- [ ] update the related code to get permissions in the decoded token from the permissions key instead of the scope (`parsePermissions.js`, `verifyUserNickname.js`, **any other relevant file**)
- [ ] Check the **getUsers** endpoint and instance files

**Comment by heliofreitastw** [comment] 2024-04-05 18:55
The card [#542](https://github.com/PublicDataWorks/complaint-manager/issues/542) was created to proceed with the implementation of the discoveries of this card.

**Closed** 2024-04-05 20:03 UTC
Labels: spike, 2 points
